import React, { useState } from "react";
import { motion, AnimatePresence } from "motion/react";
import { Copy, Download, Check, Share2, FileText, Calendar } from "lucide-react";

interface RescueBlock {
  hour_range: string;
  task: string;
  type: "build" | "test" | "deploy" | "pitch" | "write" | "review" | "format" | "submit" | "analyze" | "synthesize" | "cite" | "draft" | "design" | "rehearse" | "record" | "finalize" | "debug";
}

interface ExportPanelProps {
  goal: string;
  availableHours: number | "";
  riskLevel: string;
  keepFeatures: string[];
  cutFeatures: string[];
  successChanceBefore: number;
  successChanceAfter: number;
  rescueBlocks: RescueBlock[];
  bufferHours: number;
}

export default function ExportPanel({
  goal,
  availableHours,
  riskLevel,
  keepFeatures,
  cutFeatures,
  successChanceBefore,
  successChanceAfter,
  rescueBlocks,
  bufferHours,
}: ExportPanelProps) {
  const [copiedPlan, setCopiedPlan] = useState(false);
  const [copiedSlack, setCopiedSlack] = useState(false);
  const [expanded, setExpanded] = useState(false);

  const generateMarkdown = () => {
    const now = new Date();
    const dateStr = now.toLocaleDateString("en-US", { weekday: "short", month: "short", day: "numeric" });
    const timeStr = now.toLocaleTimeString("en-US", { hour: "2-digit", minute: "2-digit" });

    return `# 🔥 Phoenix Rescue Plan
**Generated:** ${dateStr} at ${timeStr}
**Goal:** ${goal}
**Deadline in:** ${availableHours}h
**Risk Level:** ${riskLevel}

---

## ✅ Survival Feature List (Ship These Only)
${keepFeatures.map((f) => `- [x] ${f}`).join("\n")}

## ✕ Cut / Defer to v2
${cutFeatures.map((f) => `- [ ] ~~${f}~~`).join("\n")}

**Success odds jump:** ${successChanceBefore}% → ${successChanceAfter}% (+${successChanceAfter - successChanceBefore}%)

---

## ⏱ Hour-by-Hour Execution Plan

${rescueBlocks
  .map((b) => `### ${b.hour_range} [${b.type.toUpperCase()}]\n${b.task}`)
  .join("\n\n")}

${bufferHours > 0 ? `\n**Buffer:** ${bufferHours}h — use for final testing & polish` : "\n**Note:** No buffer — execute exactly as planned"}

---
*Phoenix · Deadline Trauma Operations Center · Gemini Powered*`;
  };

  const generateSlackMessage = () => {
    const jumpVal = successChanceAfter - successChanceBefore;
    return `🔥 *Phoenix Rescue Plan* | Goal: ${goal} | ${availableHours}h left | Risk: *${riskLevel}*

✅ *Shipping:* ${keepFeatures.slice(0, 3).join(", ")}${keepFeatures.length > 3 ? ` +${keepFeatures.length - 3} more` : ""}
✕ *Deferred:* ${cutFeatures.slice(0, 2).join(", ")}${cutFeatures.length > 2 ? ` +${cutFeatures.length - 2} more` : ""}
📈 *Odds:* ${successChanceBefore}% → ${successChanceAfter}% (+${jumpVal > 0 ? jumpVal : 0}% survival jump)

⏱ *Plan:*
${rescueBlocks
  .slice(0, 4)
  .map((b) => `• ${b.hour_range}: ${b.task.slice(0, 60)}${b.task.length > 60 ? "…" : ""}`)
  .join("\n")}

_Generated by Phoenix · Gemini Powered_`;
  };

  const handleCopyPlan = async () => {
    try {
      await navigator.clipboard.writeText(generateMarkdown());
      setCopiedPlan(true);
      setTimeout(() => setCopiedPlan(false), 2000);
    } catch {
      // fallback
    }
  };

  const handleCopySlack = async () => {
    try {
      await navigator.clipboard.writeText(generateSlackMessage());
      setCopiedSlack(true);
      setTimeout(() => setCopiedSlack(false), 2000);
    } catch {
      // fallback
    }
  };

  const handleDownload = () => {
    const content = generateMarkdown();
    const blob = new Blob([content], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    const safeGoal = goal.slice(0, 30).replace(/[^a-z0-9]/gi, "-").toLowerCase();
    a.href = url;
    a.download = `phoenix-rescue-${safeGoal}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="mt-6 bg-zinc-950/60 border border-zinc-800/80 rounded-xl overflow-hidden">
      {/* Header — always visible */}
      <button
        type="button"
        onClick={() => setExpanded((v) => !v)}
        className="w-full flex items-center justify-between px-4 py-3 hover:bg-zinc-900/40 transition-colors"
      >
        <div className="flex items-center gap-2">
          <Share2 className="w-4 h-4 text-orange-400" />
          <span className="text-[11px] font-mono uppercase tracking-wider text-zinc-300 font-semibold">
            Export & Share Rescue Plan
          </span>
        </div>
        <span className="text-[10px] font-mono text-zinc-600">{expanded ? "▲ collapse" : "▼ expand"}</span>
      </button>

      <AnimatePresence>
        {expanded && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: "auto", opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.25 }}
            className="overflow-hidden"
          >
            <div className="px-4 pb-4 pt-1 grid grid-cols-1 sm:grid-cols-3 gap-3">
              {/* Copy Markdown */}
              <button
                type="button"
                onClick={handleCopyPlan}
                className="flex flex-col items-center gap-2 bg-zinc-900/60 hover:bg-zinc-800/80 border border-zinc-800 hover:border-zinc-700 rounded-xl p-4 transition-all group"
              >
                <div className="p-2 bg-zinc-800 rounded-lg group-hover:bg-zinc-700 transition-colors">
                  {copiedPlan ? (
                    <Check className="w-4 h-4 text-emerald-400" />
                  ) : (
                    <Copy className="w-4 h-4 text-zinc-400" />
                  )}
                </div>
                <div className="text-center">
                  <div className="text-xs font-semibold text-zinc-200">
                    {copiedPlan ? "Copied!" : "Copy as Markdown"}
                  </div>
                  <div className="text-[10px] text-zinc-600 font-mono mt-0.5">Notion / Obsidian ready</div>
                </div>
              </button>

              {/* Slack / Teams copy */}
              <button
                type="button"
                onClick={handleCopySlack}
                className="flex flex-col items-center gap-2 bg-zinc-900/60 hover:bg-zinc-800/80 border border-zinc-800 hover:border-zinc-700 rounded-xl p-4 transition-all group"
              >
                <div className="p-2 bg-zinc-800 rounded-lg group-hover:bg-zinc-700 transition-colors">
                  {copiedSlack ? (
                    <Check className="w-4 h-4 text-emerald-400" />
                  ) : (
                    <FileText className="w-4 h-4 text-zinc-400" />
                  )}
                </div>
                <div className="text-center">
                  <div className="text-xs font-semibold text-zinc-200">
                    {copiedSlack ? "Copied!" : "Copy for Slack"}
                  </div>
                  <div className="text-[10px] text-zinc-600 font-mono mt-0.5">Team-ready summary</div>
                </div>
              </button>

              {/* Download .md */}
              <button
                type="button"
                onClick={handleDownload}
                className="flex flex-col items-center gap-2 bg-zinc-900/60 hover:bg-zinc-800/80 border border-zinc-800 hover:border-zinc-700 rounded-xl p-4 transition-all group"
              >
                <div className="p-2 bg-zinc-800 rounded-lg group-hover:bg-zinc-700 transition-colors">
                  <Download className="w-4 h-4 text-zinc-400 group-hover:text-orange-400 transition-colors" />
                </div>
                <div className="text-center">
                  <div className="text-xs font-semibold text-zinc-200">Download .md</div>
                  <div className="text-[10px] text-zinc-600 font-mono mt-0.5">Full plan as file</div>
                </div>
              </button>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}